#!/usr/bin/env python3
"""Generate the README "Pick a skill" block + the CATALOG.md file from one source.

Source of truth:
  - each published skill.json's `metadata.{family,function,catalog_order,catalog_summary}`
  - catalog/catalog.json (family-level prose + the routing matrix)

The README "Pick a skill" block lives between sentinel markers, and CATALOG.md is
a fully generated file — both are *generated*, never hand-edited. This is the same
anti-drift discipline as the instruction-surface and shared-content symlink checks
(W8): one source, mechanically enforced.

Usage:
  python3 scripts/build-catalog.py            # --check (default): fail if README/CATALOG.md stale
  python3 scripts/build-catalog.py --check    #   same
  python3 scripts/build-catalog.py --write     # regenerate README §Pick a skill + CATALOG.md

Run by `just check` and CI in --check mode.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

from catalog_taxonomy import CatalogTaxonomy

ROOT = Path(__file__).resolve().parents[1]
README = ROOT / "README.md"
CATALOG_DOC = ROOT / "CATALOG.md"
CATALOG = ROOT / "catalog" / "catalog.json"
TAXONOMY = CatalogTaxonomy(ROOT)

BACKTICK_RE = re.compile(r"`([^`]+)`")


def fail(failures: list[str], message: str) -> None:
    failures.append(message)
    print(f"FAIL {message}", file=sys.stderr)


def sort_key(item: tuple[str, dict]):
    name, meta = item
    return (meta.get("catalog_order", 10**6), name)


def render_bullet(name: str, meta: dict) -> str:
    fn = meta.get("function")
    summary = meta.get("catalog_summary", "")
    tag = f" *({fn})*" if fn in ("audit", "design") else ""
    return f"- **`{name}`**{tag} — {summary}"


def render_table(columns: list[str], rows: list[list[str]]) -> list[str]:
    out = ["| " + " | ".join(columns) + " |", "|" + "---|" * len(columns)]
    for row in rows:
        out.append("| " + " | ".join(row) + " |")
    return out


def render_pick_a_skill(cat: dict) -> str:
    p = cat["pick_a_skill"]
    lines = ["## Pick a skill", "", p["intro"], ""]
    primary = p["primary"]
    lines += render_table(primary["columns"],
                          [[r["surface"], r["critique"], r["design"]]
                           for r in primary["rows"]])
    sec = p["secondary"]
    lines += ["", sec["lead"], ""]
    lines += render_table(sec["columns"],
                          [[r["need"], r["skill"]] for r in sec["rows"]])
    lines += [""] + p["unsure"]
    return "\n".join(lines)


def render_catalog_doc(cat: dict, skills: dict[str, dict]) -> str:
    """Render the standalone CATALOG.md file (H1 title, families as H2)."""
    c = cat["catalog"]
    lines = [
        "<!-- GENERATED by scripts/build-catalog.py from catalog/catalog.json + each "
        "skill.json's metadata.catalog_summary. Do not edit by hand; "
        "run: python3 scripts/build-catalog.py --write -->",
        "",
        "# Catalog",
        "",
        c["lead_in"],
    ]
    for fam in c["families"]:
        lines += ["", f"## {fam['title']}"]
        if fam.get("intro"):
            lines += [""] + fam["intro"]
        members = sorted(
            ((n, m) for n, m in skills.items() if m.get("family") == fam["id"]),
            key=sort_key,
        )
        if members:
            lines.append("")
            lines += [render_bullet(n, m) for n, m in members]
    return "\n".join(lines) + "\n"


def matrix_skill_refs(cat: dict) -> set[str]:
    refs: set[str] = set()
    p = cat["pick_a_skill"]
    cells = []
    for r in p["primary"]["rows"]:
        cells += [r["critique"], r["design"]]
    for r in p["secondary"]["rows"]:
        cells.append(r["skill"])
    for cell in cells:
        refs.update(BACKTICK_RE.findall(cell))
    return refs


def replace_block(text: str, marker: str, body: str, failures: list[str]) -> str:
    begin = f"<!-- BEGIN GENERATED: {marker} (scripts/build-catalog.py) -->"
    end = f"<!-- END GENERATED: {marker} -->"
    pattern = re.compile(
        re.escape(begin) + r"\n.*?\n" + re.escape(end), re.DOTALL
    )
    if not pattern.search(text):
        fail(failures, f"README.md is missing the '{marker}' generated markers "
                       f"({begin} ... {end})")
        return text
    return pattern.sub(begin + "\n" + body + "\n" + end, text)


def extract_block(text: str, marker: str) -> str | None:
    begin = f"<!-- BEGIN GENERATED: {marker} (scripts/build-catalog.py) -->"
    end = f"<!-- END GENERATED: {marker} -->"
    m = re.search(re.escape(begin) + r"\n(.*?)\n" + re.escape(end), text, re.DOTALL)
    return m.group(1) if m else None


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--check", action="store_true", help="fail if README is stale (default)")
    g.add_argument("--write", action="store_true", help="regenerate the README sections")
    args = ap.parse_args()
    write = args.write

    failures: list[str] = []
    cat = json.loads(CATALOG.read_text())
    skills = TAXONOMY.public_skill_metadata()
    for failure in TAXONOMY.validate():
        fail(failures, failure)

    # cross-check: every skill named in the routing matrix exists
    known = set(skills)
    for ref in sorted(matrix_skill_refs(cat)):
        if ref not in known:
            fail(failures, f"catalog/catalog.json matrix references unknown skill "
                           f"`{ref}` (not a published skill)")
    # cross-check: every catalog family has at least one skill
    for fam in cat["catalog"]["families"]:
        if not any(m.get("family") == fam["id"] for m in skills.values()):
            fail(failures, f"catalog family {fam['id']!r} has no skills")

    if failures:
        print(f"\nbuild-catalog: {len(failures)} validation failure(s).", file=sys.stderr)
        return 1

    pick = render_pick_a_skill(cat)
    catalog_doc = render_catalog_doc(cat, skills)

    text = README.read_text()
    new_text = replace_block(text, "pick-a-skill", pick, failures)
    if failures:
        return 1
    current_catalog = CATALOG_DOC.read_text() if CATALOG_DOC.exists() else None

    if write:
        wrote = []
        if new_text != text:
            README.write_text(new_text)
            wrote.append("README.md")
        if catalog_doc != current_catalog:
            CATALOG_DOC.write_text(catalog_doc)
            wrote.append("CATALOG.md")
        print(f"build-catalog: regenerated {', '.join(wrote)}." if wrote
              else "build-catalog: README.md + CATALOG.md already up to date.")
        return 0

    # --check (default)
    stale = []
    if extract_block(text, "pick-a-skill") != pick:
        stale.append("README.md §Pick a skill")
    if catalog_doc != current_catalog:
        stale.append("CATALOG.md")
    if stale:
        print(f"FAIL build-catalog: out of date: {', '.join(stale)}", file=sys.stderr)
        print("      fix: python3 scripts/build-catalog.py --write", file=sys.stderr)
        return 1
    print(f"OK:   README §Pick a skill + CATALOG.md in sync with "
          f"skill.json + catalog/catalog.json ({len(skills)} skills)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
